INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME)
VALUES(1234, 'OYKU', 'AKKOYUN');

INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME)
VALUES(9821, 'TIM', 'SMITH');

INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME)
VALUES(3309, 'ROSE', 'SMITH');