spring:
  application:
    name: simple-banking-transaction-service
  datasource:
    url: jdbc:h2:mem:transactionsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

app:
  feign:
    client:
      simple-banking: simple-banking-service